const sampleData = {
  educations: [
    {
      school: "IESE Business School",
      degree: "Master of Business Administration (MBA)",
      period: "Apr 2023 – Sep 2024",
      logo: "/IESE.png",
    },
    {
      school: "Strathmore University",
      degree: "Owner Manager Programme",
      period: "2019",
      logo: "/cim.png",
    },
    {
      school: "Lagos Business School, Pan-Atlantic University",
      degree: "Certification in New Product Development",
      period: "2007",
      logo: "/pan.jpeg",
    },
    {
      school: "Nnamdi Azikiwe University",
      degree: "Bachelor's Degree in Political Science and Government",
      period: "2000 – 2004",
      logo: "/awka.png",
    },
    {
      school: "Chartered Institute of Marketing, UK",
      degree: "Post Graduate Diploma (PGD)",
      period: "",
      logo: "/cim.png",
    },
  ],
  experience: [
    {
      company: "Zuri Health",
      logo: "/zuri.png",
      role: "Founder and CEO",
      period: "Jan 2020 - Present · 5 yrs 7 mos",
      location: "Kenya",
      description: [
        "Working with a talented team building a comprehensive mobile health solution.",
        "Addressing Africa's health infrastructure and cost challenges.",
      ],
    },
    {
      company: "Play Group (Taurus Group LTD)",
      logo: "/playgroup.png",
      role: "Founder and CEO",
      period: "Jan 2013 - Present · 12 yrs 7 mos",
      location: "Nairobi, Kenya",
      description: [
        "Built Africa’s first integrated entertainment business: Play, Taurus Musik, and Taurus Events.",
        "Led finance, HR, and created multi-revenue stream operations.",
      ],
    },
    {
      company: "MTech Communications PLC",
      logo: "/mtech.jpeg",
      role: "Executive Director Group Commercialization",
      period: "Oct 2011 - Jan 2013 · 1 yr 4 mos",
      location: "Nairobi, Kenya",
      description: [
        "Expanded into Francophone & Southern Africa.",
        "Launched Airtel Africa partnership and grew revenue to $5M+.",
        "Led Africa’s content aggregation growth.",
      ],
    },
    {
      company: "MTech Communications PLC",
      logo: "/mtech.jpeg",
      role: "Chief Executive Officer, East Africa",
      period: "Oct 2008 - Jan 2013 · 4 yrs 4 mos",
      location: "Nairobi, Kenya",
      description: [
        "Revived East Africa branch from bankruptcy to profitability.",
        "Launched new VAS products and $1M+ in new partnerships.",
      ],
    },
    {
      company: "MTech Communications PLC",
      logo: "/mtech.jpeg",
      role: "Senior Product Development Executive for Africa",
      period: "Apr 2007 - Jul 2008 · 1 yr 4 mos",
      location: "Lagos, Nigeria",
      description: [
        "Led development of interactive media in Kenya, Uganda, Ghana.",
        "Pioneered performance dashboards and key content alliances.",
      ],
    },
  ],
  skill: [
    {title: "Mobile Content"},
    {title: "VAS"},
    {title: "Telecommunications"},
    {title: "Mobile Entertainment"},
    {title: "Mobile Applications"},
    {title: "Strategy"},
    {title: "Mobile Devices"},
    {title: "Mobile Marketing"},
    {title: "SMS"},
    {title: "Entrepreneurship"},
    {title: "Mobile Internet"},
    {title:  "Business Strategy"},
    {title:  "Project Management"},
    {title:  "Project Planning"},
    {title:  "Strategic Partnerships"},
    {title: "Product Development"},
    {title: "Product Management"},
    {title: "New Business Development"},
    {title: "Product Marketing"},
    {title: "Mobile Commerce"},
    {title: "Leadership"},
    {title: "Management"},
    {title: "Start-ups"},
    {title: "Marketing"},
    {title: "Cross-functional Team Leadership"},
    {title: "Strategic Planning"},
    {title: "Market Research"},
    {title: "Advertising"},
    {title: "E-commerce"},
    {title: "Customer Relationship Management (CRM)"},
    {title: "Business Development"},
    {title: "Value-Added Services (VAS)"},
    {title: "Team Leadership"},
    {title: "Team Management"},
    {title: "Business Planning"},
    {title: "Digital Marketing"},
    {title: "Social Media Marketing"},
    {title: "Negotiation"},
    {title: "Public Relations"},
    {title: "Microsoft Office"},
    {title: "Social Media"},
    {title: "Competitive Analysis"},
    {title: "Online Marketing"},
    {title: "Multi-channel Marketing"},
    {title: "P&L Management"},
    {title: "Customer Service"},
    {title:  "Event Management"},
    {title: "Sales"},
    {title: "Wireless Technologies"},
  ],
};


export default sampleData